/** Track parser code and selectors independently; deployed revisions remain observable. */
import { z } from "zod";

/** Parser code is a submodule; selectors retain their independently updated Git dependency. */
export const upstreams = [
  { package: "nodestone-upstream", repository: "xivapi/nodestone" },
  { package: "lodestone-css-selectors", repository: "xivapi/lodestone-css-selectors" },
] as const;

/** This small build artifact records full commits and is regenerated by the update workflow. */
export const revisionsSchema = z.record(
  z.string(),
  z.object({
    repository: z.string(),
    revision: z.string().regex(/^[0-9a-f]{40}$/),
    sourceHash: z
      .string()
      .regex(/^[0-9a-f]{64}$/)
      .optional(),
  }),
);
export type Revisions = z.infer<typeof revisionsSchema>;
export interface UpstreamState {
  status: "checking" | "current" | "update_available" | "unavailable";
  checkedAt: string | null;
  components: {
    package: string;
    repository: string;
    deployed: string;
    latest: string;
    current: boolean;
  }[];
}

/** Resolve public upstream HEAD without credentials or a git executable in the runtime image. */
export async function latestRevision(repository: string, signal: AbortSignal): Promise<string> {
  const response = await fetch(`https://api.github.com/repos/${repository}/commits/HEAD`, {
    headers: { accept: "application/vnd.github+json", "user-agent": "TaruBot-upstream-monitor" },
    signal: AbortSignal.any([signal, AbortSignal.timeout(15000)]),
  });
  if (!response.ok)
    throw new Error(`Upstream check failed for ${repository} (${response.status}).`);
  return z.object({ sha: z.string().regex(/^[0-9a-f]{40}$/) }).parse(await response.json()).sha;
}

/** Read only the selected Git resolutions from Bun's generated JSONC lockfile. */
export function lockedRevisions(raw: unknown): Record<string, string> {
  const lock = z.object({ packages: z.record(z.string(), z.array(z.unknown())) }).parse(raw);
  const parser = z.string().parse(lock.packages["nodestone-upstream"]?.[0]);
  if (!parser.endsWith("@file:vendor/nodestone"))
    throw new Error("Nodestone must resolve from the vendor/nodestone submodule.");
  return Object.fromEntries(
    upstreams
      .filter((upstream) => upstream.package !== "nodestone-upstream")
      .map((upstream) => {
        const resolution = z.string().parse(lock.packages[upstream.package]?.[0]);
        const commit = /#([0-9a-f]{7,40})$/.exec(resolution)?.[1];
        if (!commit) throw new Error(`Missing Git revision for ${upstream.package} in bun.lock.`);
        return [upstream.package, commit];
      }),
  );
}

/** Keep a periodic cached health result; probes themselves never trigger upstream traffic. */
export class UpstreamMonitor {
  private state: UpstreamState = { status: "checking", checkedAt: null, components: [] };
  private timer: ReturnType<typeof setInterval> | undefined;
  private readonly cancellation = new AbortController();
  private running = false;

  constructor(
    private readonly deployed: Revisions,
    private readonly resolve: typeof latestRevision = latestRevision,
    private readonly report: (state: UpstreamState) => void = () => {},
  ) {}

  /** The returned state is read-only presentation data, independent of parser readiness. */
  status(): UpstreamState {
    return structuredClone(this.state);
  }

  /** A changed selector repository is enough to report an available update. */
  async check(): Promise<void> {
    if (this.running || this.cancellation.signal.aborted) return;
    this.running = true;
    const previous = this.state.status;
    try {
      const components = await Promise.all(
        upstreams.map(async (upstream) => {
          const deployed = this.deployed[upstream.package];
          if (!deployed || deployed.repository !== upstream.repository)
            throw new Error("Missing deployed revision metadata.");
          const latest = await this.resolve(upstream.repository, this.cancellation.signal);
          return {
            ...upstream,
            deployed: deployed.revision,
            latest,
            current: deployed.revision === latest,
          };
        }),
      );
      this.state = {
        status: components.every((component) => component.current) ? "current" : "update_available",
        checkedAt: new Date().toISOString(),
        components,
      };
    } catch {
      // GitHub outages affect update visibility, not otherwise available Discord/Lodestone work.
      this.state = { ...this.state, status: "unavailable", checkedAt: new Date().toISOString() };
    } finally {
      this.running = false;
    }
    if (previous !== this.state.status) this.report(this.status());
  }

  /** Check at startup and on a bounded interval; zero supports deliberately offline deployments. */
  start(seconds: number): void {
    if (seconds === 0) return;
    void this.check();
    this.timer = setInterval(() => {
      void this.check();
    }, seconds * 1000);
  }

  /** Stop monitoring and cancel pending GitHub requests during sidecar shutdown. */
  stop(): void {
    this.cancellation.abort();
    if (this.timer) clearInterval(this.timer);
  }
}
